
services:
  dongguatv:
    build: .
    container_name: dongguatv
    restart: unless-stopped
    ports:
    - "30031:30031"
    environment:
    #- PORT=30031
    - TMDB_API_KEY=key
    - ADMIN_PASSWORD=admin
